import type { PlaceWithPolicy } from "@/lib/types";

/**
 * Curated South Florida fixtures — same set as supabase/seed.sql.
 * Used when Supabase env is unset so Explore still works offline.
 */
export const SOUTH_FLORIDA_PLACES: PlaceWithPolicy[] = [
  {
    id: "a1000000-0000-4000-8000-000000000001",
    name: "Red Reef Park",
    slug: "red-reef-park-boca-raton",
    category: "park",
    lat: 26.3558,
    lng: -80.0705,
    countryCode: "US",
    address: "1400 N Ocean Blvd",
    city: "Boca Raton",
    region: "FL",
    website: "https://www.myboca.us/Facilities/Facility/Details/Red-Reef-Park-7",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000001",
      dogStatus: "dogs_ok_with_restrictions",
      access: ["outdoor", "paths", "beach_adjacent"],
      maxDogs: null,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: true,
      advanceApprovalRequired: false,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Leashed dogs on park paths; confirm beach zone rules before bringing Sugar and Munch.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.8,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000002",
    name: "Spanish River Park",
    slug: "spanish-river-park-boca-raton",
    category: "park",
    lat: 26.3855,
    lng: -80.0692,
    countryCode: "US",
    address: "3001 N Ocean Blvd",
    city: "Boca Raton",
    region: "FL",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000002",
      dogStatus: "dogs_welcome",
      access: ["outdoor", "paths", "picnic"],
      maxDogs: null,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: true,
      advanceApprovalRequired: false,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Good dual-dog outing; keep both leashed on trails and near playgrounds.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.75,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000003",
    name: "Lauderdale-by-the-Sea Dog Beach",
    slug: "lauderdale-by-the-sea-dog-beach",
    category: "beach",
    lat: 26.1915,
    lng: -80.094,
    countryCode: "US",
    address: "El Prado Park / oceanfront",
    city: "Lauderdale-by-the-Sea",
    region: "FL",
    website: "https://www.lbts-fl.gov/",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000003",
      dogStatus: "dogs_welcome",
      access: ["beach", "off_leash_zone", "outdoor"],
      maxDogs: null,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: false,
      advanceApprovalRequired: false,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Designated dog beach hours/rules apply. Works well for Sugar + Munch together.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.85,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000004",
    name: "Barkingham Dog Park",
    slug: "barkingham-dog-park-fort-lauderdale",
    category: "park",
    lat: 26.118,
    lng: -80.1508,
    countryCode: "US",
    address: "1600 SW 15th Ave",
    city: "Fort Lauderdale",
    region: "FL",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000004",
      dogStatus: "dogs_welcome",
      access: ["outdoor", "fenced", "off_leash_zone"],
      maxDogs: null,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: false,
      advanceApprovalRequired: false,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Separate small/large areas — useful if Sugar and Munch prefer different play styles.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.8,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000005",
    name: "The Salty Donut Wynwood",
    slug: "salty-donut-wynwood-miami",
    category: "cafe",
    lat: 25.8007,
    lng: -80.1998,
    countryCode: "US",
    address: "3451 NE 1st Ave",
    city: "Miami",
    region: "FL",
    website: "https://www.saltydonut.com/",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000005",
      dogStatus: "dogs_ok_outdoors",
      access: ["patio", "outdoor_seating"],
      maxDogs: 2,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: true,
      advanceApprovalRequired: false,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Patio dogs typically OK. Confirm capacity for two dogs (Sugar + Munch) at peak times.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.7,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000006",
    name: "Yardbird Southern Table & Bar",
    slug: "yardbird-miami-beach",
    category: "restaurant",
    lat: 25.7908,
    lng: -80.14,
    countryCode: "US",
    address: "1600 Lenox Ave",
    city: "Miami Beach",
    region: "FL",
    website: "https://www.runchickenrun.com/miami/",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000006",
      dogStatus: "ask_first",
      access: ["patio"],
      maxDogs: 1,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: true,
      advanceApprovalRequired: true,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Ask first: patio dog policy often max_dogs=1. Bring Sugar or Munch alone unless staff approves both.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.65,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000007",
    name: "Kimpton Surfer Hotel",
    slug: "kimpton-surfer-hotel-miami-beach",
    category: "hotel",
    lat: 25.779,
    lng: -80.1295,
    countryCode: "US",
    address: "1052 Collins Ave",
    city: "Miami Beach",
    region: "FL",
    website: "https://www.surferhotel.com/",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000007",
      dogStatus: "dogs_ok_with_restrictions",
      access: ["rooms", "lobby", "outdoor"],
      maxDogs: 2,
      maxWeightKg: 36,
      maxCombinedWeightKg: 45,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: true,
      advanceApprovalRequired: true,
      feeType: "flat",
      feeAmount: 150,
      feeCurrency: "USD",
      exceptionText:
        "Pet fee; confirm combined weight for Sugar + Munch and advance approval before booking.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.75,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
  {
    id: "a1000000-0000-4000-8000-000000000008",
    name: "Mizner Park Amphitheater Lawn",
    slug: "mizner-park-lawn-boca-raton",
    category: "park",
    lat: 26.362,
    lng: -80.0855,
    countryCode: "US",
    address: "590 Plaza Real",
    city: "Boca Raton",
    region: "FL",
    status: "active",
    sourceType: "curated",
    sourceAttribution: "Dogmarked curated seed",
    policy: {
      placeId: "a1000000-0000-4000-8000-000000000008",
      dogStatus: "dogs_ok_with_restrictions",
      access: ["outdoor", "lawn"],
      maxDogs: null,
      maxWeightKg: null,
      maxCombinedWeightKg: null,
      smallDogsOnly: false,
      carrierRequired: false,
      leashRequired: true,
      advanceApprovalRequired: false,
      feeType: "none",
      feeAmount: null,
      feeCurrency: "USD",
      exceptionText:
        "Leashed dogs on public lawn areas; event days may restrict access.",
      sourceType: "curated",
      sourceUrl: null,
      confidence: 0.7,
      lastVerifiedAt: "2026-06-01T00:00:00.000Z",
    },
  },
];

export const DEFAULT_DOG_PROFILES = [
  {
    id: "local-sugar",
    name: "Sugar",
    weightKg: 8.2,
    sizeClass: "small" as const,
    travelsInCarrier: true,
  },
  {
    id: "local-munch",
    name: "Munch",
    weightKg: 22.5,
    sizeClass: "medium" as const,
    travelsInCarrier: false,
  },
];
